version: "3.9"

services:

  fastapi:
    build: ./fastapi_service
    ports:
      - "8000:8000"
    environment:
      - PINECONE_API_KEY=your_key
      - GEMINI_API_KEY=your_key

  django:
    build: ./django_chat
    ports:
      - "8001:8001"
    depends_on:
      - fastapi