services:
  - type: web
    name: django-rag
    env: python
    rootDir: django_chat

    buildCommand: pip install -r requirements.txt

    startCommand: >
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python -m daphne -b 0.0.0.0 -p $PORT django_chat.asgi:application