# Generated by Django 5.2.12 on 2026-03-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pinecone_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
