# Generated by Django 5.2.12 on 2026-04-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_document_embedding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
